CREATE TABLE rol (
  rol_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rol_nombre TEXT NOT NULL UNIQUE,
  CONSTRAINT chk_rol_nombre CHECK (rol_nombre IN ('administrador', 'gerencia', 'despachador'))
);  
CREATE TABLE usuario (
  usr_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usr_nombre VARCHAR(100) NOT NULL,
  usr_correo VARCHAR(100) NOT NULL UNIQUE,
  usr_contrasena VARCHAR(255) NOT NULL,
  usr_estado TEXT NOT NULL DEFAULT 'activo',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT chk_usr_estado CHECK (usr_estado IN ('activo', 'inactivo'))
);

CREATE TABLE usuario_rol (
  uro_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usr_id BIGINT NOT NULL,
  rol_id BIGINT NOT NULL,
  CONSTRAINT unique_usuario_rol UNIQUE (usr_id, rol_id),
  CONSTRAINT fk_usuario_rol_usuario FOREIGN KEY (usr_id) REFERENCES usuario(usr_id) ON DELETE CASCADE,
  CONSTRAINT fk_usuario_rol_rol FOREIGN KEY (rol_id) REFERENCES rol(rol_id) ON DELETE CASCADE
);

-- ============================================================
-- 2. TRANSPORTE UNIFICADO
-- ============================================================
CREATE TABLE transportista (
  tra_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tra_nombre VARCHAR(100) NOT NULL,
  tra_apellido VARCHAR(100) NOT NULL,
  tra_tipo TEXT NOT NULL,
  tra_estado TEXT NOT NULL DEFAULT 'activo',
  tra_telefono VARCHAR(20),   -- número WhatsApp internacional, ej: +593987654321
  tra_correo VARCHAR(100),    -- correo Gmail para notificaciones de alerta
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT chk_tra_tipo CHECK (tra_tipo IN ('socio', 'particular')),
  CONSTRAINT chk_tra_estado CHECK (tra_estado IN ('activo', 'inactivo'))
);

CREATE TABLE vehiculo (
  veh_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  veh_placa VARCHAR(20) NOT NULL UNIQUE,
  veh_marca VARCHAR(100) NOT NULL DEFAULT 'Desconocida',
  veh_tipo TEXT NOT NULL DEFAULT 'volqueta',
  veh_cubicaje NUMERIC(10,2) NOT NULL,
  tra_id BIGINT NOT NULL,
  veh_estado TEXT NOT NULL DEFAULT 'activa',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT fk_vehiculo_transportista FOREIGN KEY (tra_id) REFERENCES transportista(tra_id) ON DELETE RESTRICT,
  CONSTRAINT chk_veh_tipo CHECK (veh_tipo IN ('volqueta', 'cabezal')),
  CONSTRAINT chk_veh_estado CHECK (veh_estado IN ('activa', 'inactiva')),
  CONSTRAINT chk_veh_cubicaje CHECK (veh_cubicaje > 0)
);

-- ============================================================
-- 3. CATÁLOGOS BÁSICOS
-- ============================================================
CREATE TABLE lugar (
  lug_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lug_nombre VARCHAR(150) NOT NULL UNIQUE,
  lug_tipo TEXT NOT NULL,
  lug_latitud NUMERIC(10,8),
  lug_longitud NUMERIC(11,8),
  lug_estado TEXT NOT NULL DEFAULT 'activo',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT chk_lug_tipo CHECK (lug_tipo IN ('Mina', 'Stock', 'Constructora', 'Otro')),
  CONSTRAINT chk_lug_estado CHECK (lug_estado IN ('activo', 'inactivo'))
);

CREATE TABLE cliente (
  cli_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cli_nombre VARCHAR(150) NOT NULL,
  cli_correo VARCHAR(100),
  cli_telefono VARCHAR(20),
  cli_estado TEXT NOT NULL DEFAULT 'activo',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT chk_cli_estado CHECK (cli_estado IN ('activo', 'inactivo'))
);

CREATE TABLE cliente_cubicaje (
  ccu_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cli_id BIGINT NOT NULL,
  veh_id BIGINT NOT NULL,
  ccu_cubicaje NUMERIC(10,2) NOT NULL,
  CONSTRAINT unique_cliente_vehiculo UNIQUE (cli_id, veh_id),
  CONSTRAINT fk_cliente_cubicaje_cliente FOREIGN KEY (cli_id) REFERENCES cliente(cli_id) ON DELETE CASCADE,
  CONSTRAINT fk_cliente_cubicaje_vehiculo FOREIGN KEY (veh_id) REFERENCES vehiculo(veh_id) ON DELETE CASCADE,
  CONSTRAINT chk_ccu_cubicaje CHECK (ccu_cubicaje > 0)
);

CREATE TABLE material (
  mat_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mat_nombre VARCHAR(100) NOT NULL UNIQUE,
  mat_unidad VARCHAR(20) NOT NULL DEFAULT 'm3',
  mat_categoria VARCHAR(50) NOT NULL DEFAULT 'Pétreos',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================
-- 4. FLUJO CORPORATIVO: TICKETS Y PAGOS DE CRÉDITO
-- ============================================================
CREATE TABLE ticket (
  tic_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tic_numero VARCHAR(20) NOT NULL UNIQUE,
  tic_fecha DATE NOT NULL,
  veh_id BIGINT NOT NULL,
  mat_id BIGINT NOT NULL,
  tic_cubicaje NUMERIC(10,2) NOT NULL,
  lug_origen_id BIGINT NOT NULL,
  lug_destino_id BIGINT NOT NULL,
  tic_recorrido_km NUMERIC(10,2),
  cli_id BIGINT NOT NULL,
  tic_estado TEXT NOT NULL DEFAULT 'despachado',
  tic_observaciones TEXT,
  tic_condicion_climatica TEXT NOT NULL DEFAULT 'Despejado',
  tic_nivel_riesgo TEXT NOT NULL DEFAULT 'Sin Riesgo',
  tic_hora_despacho TIME,
  tic_tiempo_estimado_llegada TIME,
  tic_tiempo_real_llegada TIME,
  tic_tiempo_mora NUMERIC(5,2),
  usr_creado_por BIGINT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT fk_ticket_vehiculo FOREIGN KEY (veh_id) REFERENCES vehiculo(veh_id) ON DELETE RESTRICT,
  CONSTRAINT fk_ticket_lugar_origen FOREIGN KEY (lug_origen_id) REFERENCES lugar(lug_id),
  CONSTRAINT fk_ticket_material FOREIGN KEY (mat_id) REFERENCES material(mat_id),
  CONSTRAINT fk_ticket_cliente FOREIGN KEY (cli_id) REFERENCES cliente(cli_id),
  CONSTRAINT fk_ticket_usuario FOREIGN KEY (usr_creado_por) REFERENCES usuario(usr_id) ON DELETE SET NULL,
  CONSTRAINT chk_tic_estado CHECK (tic_estado IN ('despachado', 'recibido', 'anulado')),
  CONSTRAINT chk_tic_condicion_climatica CHECK (tic_condicion_climatica IN ('Despejado', 'Lluvia', 'Neblina', 'Deslizamiento')),
  CONSTRAINT chk_tic_nivel_riesgo CHECK (tic_nivel_riesgo IN ('Sin Riesgo', 'Tolerable', 'Moderado', 'Crítico')),
  CONSTRAINT chk_tic_cubicaje CHECK (tic_cubicaje > 0),
  CONSTRAINT chk_tic_recorrido CHECK (tic_recorrido_km IS NULL OR tic_recorrido_km >= 0),
  CONSTRAINT chk_tic_mora CHECK (tic_tiempo_mora IS NULL OR tic_tiempo_mora >= 0),
  CONSTRAINT chk_tic_origen_destino CHECK (lug_origen_id <> lug_destino_id)
);

CREATE INDEX idx_tickets_fecha ON ticket(tic_fecha);

CREATE TABLE pago (
  pag_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pag_nro VARCHAR(20) NOT NULL,
  pag_fecha DATE NOT NULL,
  tic_id BIGINT NOT NULL UNIQUE,
  pag_precio_unitario NUMERIC(10,2) NOT NULL DEFAULT 0.50,
  pag_total NUMERIC(10,2) NOT NULL,
  pag_observaciones TEXT,
  usr_creado_por BIGINT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT unique_pago_ticket UNIQUE (pag_nro, tic_id),
  CONSTRAINT fk_pago_ticket FOREIGN KEY (tic_id) REFERENCES ticket(tic_id) ON DELETE RESTRICT,
  CONSTRAINT fk_pago_usuario FOREIGN KEY (usr_creado_por) REFERENCES usuario(usr_id) ON DELETE SET NULL,
  CONSTRAINT chk_pag_precio_unitario CHECK (pag_precio_unitario >= 0),
  CONSTRAINT chk_pag_total CHECK (pag_total >= 0)
);

CREATE INDEX idx_pago_nro ON pago(pag_nro);
CREATE INDEX idx_pago_fecha ON pago(pag_fecha);

-- ============================================================
-- 5. FLUJO DE CONTADO: EXTRAS
-- ============================================================
CREATE TABLE extra (
  ext_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ext_numero VARCHAR(20) NOT NULL UNIQUE,
  ext_fecha DATE NOT NULL,
  veh_id BIGINT NOT NULL,
  ext_cubicaje NUMERIC(10,2) NOT NULL,
  mat_id BIGINT NOT NULL,
  ext_detalle TEXT,
  lug_origen_id BIGINT,
  ext_precio NUMERIC(10,2) NOT NULL,
  ext_estado TEXT NOT NULL DEFAULT 'completado',
  usr_creado_por BIGINT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT fk_extra_vehiculo FOREIGN KEY (veh_id) REFERENCES vehiculo(veh_id) ON DELETE RESTRICT,
  CONSTRAINT fk_extra_material FOREIGN KEY (mat_id) REFERENCES material(mat_id),
  CONSTRAINT fk_extra_lugar_origen FOREIGN KEY (lug_origen_id) REFERENCES lugar(lug_id) ON DELETE SET NULL,
  CONSTRAINT fk_extra_usuario FOREIGN KEY (usr_creado_por) REFERENCES usuario(usr_id) ON DELETE SET NULL,
  CONSTRAINT chk_ext_estado CHECK (ext_estado IN ('completado', 'anulado')),
  CONSTRAINT chk_ext_cubicaje CHECK (ext_cubicaje > 0),
  CONSTRAINT chk_ext_precio CHECK (ext_precio >= 0)
);

-- ============================================================
-- 6. MAQUINARIA DE LA COOPERATIVA
-- ============================================================
CREATE TABLE maquina_cooperativa (
  mac_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  mac_placa VARCHAR(20) NOT NULL UNIQUE,
  mac_tipo VARCHAR(100) NOT NULL,
  mac_marca VARCHAR(100) NOT NULL,
  mac_modelo VARCHAR(100),
  mac_estado TEXT NOT NULL DEFAULT 'activa',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT chk_mac_estado CHECK (mac_estado IN ('activa', 'inactiva'))
);

CREATE TABLE trabajo_maquinaria (
  trm_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  trm_nro_registro VARCHAR(20) NOT NULL UNIQUE,
  trm_fecha DATE NOT NULL,
  mac_id BIGINT NOT NULL,
  cli_id BIGINT,
  trm_hora_inicial TIME NOT NULL,
  trm_hora_final TIME NOT NULL,
  trm_total_horas NUMERIC(5,2) GENERATED ALWAYS AS (
    EXTRACT(EPOCH FROM (trm_hora_final - trm_hora_inicial)) / 3600
  ) STORED,
  trm_valor_hora NUMERIC(10,2) NOT NULL,
  trm_valor_facturar NUMERIC(10,2),
  trm_estado TEXT NOT NULL DEFAULT 'pendiente',
  usr_creado_por BIGINT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT fk_trabajo_maquinaria_maquina FOREIGN KEY (mac_id) REFERENCES maquina_cooperativa(mac_id),
  CONSTRAINT fk_trabajo_maquinaria_cliente FOREIGN KEY (cli_id) REFERENCES cliente(cli_id) ON DELETE SET NULL,
  CONSTRAINT fk_trabajo_maquinaria_usuario FOREIGN KEY (usr_creado_por) REFERENCES usuario(usr_id) ON DELETE SET NULL,
  CONSTRAINT chk_trm_estado CHECK (trm_estado IN ('pendiente', 'facturado', 'anulado')),
  CONSTRAINT chk_trm_horas CHECK (trm_hora_final > trm_hora_inicial),
  CONSTRAINT chk_trm_valor_hora CHECK (trm_valor_hora >= 0),
  CONSTRAINT chk_trm_valor_facturar CHECK (trm_valor_facturar IS NULL OR trm_valor_facturar >= 0)
);

ALTER TABLE rol ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT now();
ALTER TABLE usuario_rol ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT now();
ALTER TABLE cliente_cubicaje ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT now(); 

CREATE OR REPLACE FUNCTION actualizar_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_usuario_updated_at BEFORE UPDATE ON usuario FOR EACH ROW EXECUTE FUNCTION actualizar_updated_at();
CREATE TRIGGER trg_transportista_updated_at BEFORE UPDATE ON transportista FOR EACH ROW EXECUTE FUNCTION actualizar_updated_at();
CREATE TRIGGER trg_vehiculo_updated_at BEFORE UPDATE ON vehiculo FOR EACH ROW EXECUTE FUNCTION actualizar_updated_at();
CREATE TRIGGER trg_lugar_updated_at BEFORE UPDATE ON lugar FOR EACH ROW EXECUTE FUNCTION actualizar_updated_at();
CREATE TRIGGER trg_cliente_updated_at BEFORE UPDATE ON cliente FOR EACH ROW EXECUTE FUNCTION actualizar_updated_at();
CREATE TRIGGER trg_material_updated_at BEFORE UPDATE ON material FOR EACH ROW EXECUTE FUNCTION actualizar_updated_at();
CREATE TRIGGER trg_ticket_updated_at BEFORE UPDATE ON ticket FOR EACH ROW EXECUTE FUNCTION actualizar_updated_at();

CREATE OR REPLACE VIEW vista_ticket_detalle AS
SELECT
  t.*,
  lo.lug_nombre AS origen_nombre,
  ld.lug_nombre AS destino_nombre,
  cc.ccu_cubicaje AS cliente_cubicaje
FROM ticket t
LEFT JOIN lugar lo ON lo.lug_id = t.lug_origen_id
LEFT JOIN lugar ld ON ld.lug_id = t.lug_destino_id
LEFT JOIN cliente_cubicaje cc ON cc.cli_id = t.cli_id AND cc.veh_id = t.veh_id; 

ALTER TABLE usuario ADD COLUMN IF NOT EXISTS auth_user_id UUID UNIQUE;
CREATE INDEX IF NOT EXISTS idx_usuario_auth_user_id ON usuario(auth_user_id);

CREATE OR REPLACE FUNCTION public.usuario_tiene_rol(p_rol TEXT)
RETURNS BOOLEAN LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT EXISTS (
    SELECT 1 FROM usuario u
    JOIN usuario_rol ur ON ur.usr_id = u.usr_id
    JOIN rol r ON r.rol_id = ur.rol_id
    WHERE u.auth_user_id = auth.uid() AND u.usr_estado = 'activo' AND r.rol_nombre = p_rol
  );
$$;

REVOKE ALL ON FUNCTION public.usuario_tiene_rol(TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.usuario_tiene_rol(TEXT) TO authenticated;

CREATE OR REPLACE FUNCTION public.usuario_tiene_alguno(p_roles TEXT[])
RETURNS BOOLEAN LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT EXISTS (
    SELECT 1 FROM usuario u
    JOIN usuario_rol ur ON ur.usr_id = u.usr_id
    JOIN rol r ON r.rol_id = ur.rol_id
    WHERE u.auth_user_id = auth.uid() AND u.usr_estado = 'activo' AND r.rol_nombre = ANY(p_roles)
  );
$$;

REVOKE ALL ON FUNCTION public.usuario_tiene_alguno(TEXT[]) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.usuario_tiene_alguno(TEXT[]) TO authenticated;

CREATE OR REPLACE FUNCTION public.mis_roles()
RETURNS TEXT[] LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT COALESCE(array_agg(r.rol_nombre), ARRAY[]::TEXT[])
  FROM usuario u
  JOIN usuario_rol ur ON ur.usr_id = u.usr_id
  JOIN rol r ON r.rol_id = ur.rol_id
  WHERE u.auth_user_id = auth.uid() AND u.usr_estado = 'activo';
$$;

REVOKE ALL ON FUNCTION public.mis_roles() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.mis_roles() TO authenticated;

DO $$
DECLARE
  pol RECORD;
BEGIN
  FOR pol IN
    SELECT schemaname, tablename, policyname
    FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename IN (
        'rol', 'usuario', 'usuario_rol', 'transportista', 'vehiculo', 'lugar', 'cliente', 'material', 'cliente_cubicaje', 'ticket', 'pago', 'extra', 'maquina_cooperativa', 'trabajo_maquinaria'
      )
  LOOP
    EXECUTE format('DROP POLICY IF EXISTS %I ON %I.%I', pol.policyname, pol.schemaname, pol.tablename);
  END LOOP;
END $$;

REVOKE ALL ON TABLE rol FROM anon;
REVOKE ALL ON TABLE usuario FROM anon;
REVOKE ALL ON TABLE usuario_rol FROM anon;
REVOKE ALL ON TABLE transportista FROM anon;
REVOKE ALL ON TABLE vehiculo FROM anon;
REVOKE ALL ON TABLE lugar FROM anon;
REVOKE ALL ON TABLE cliente FROM anon;
REVOKE ALL ON TABLE material FROM anon;
REVOKE ALL ON TABLE cliente_cubicaje FROM anon;
REVOKE ALL ON TABLE ticket FROM anon;
REVOKE ALL ON TABLE pago FROM anon;
REVOKE ALL ON TABLE extra FROM anon;
REVOKE ALL ON TABLE maquina_cooperativa FROM anon;
REVOKE ALL ON TABLE trabajo_maquinaria FROM anon;

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE rol TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE usuario TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE usuario_rol TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE transportista TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE vehiculo TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE lugar TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE cliente TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE material TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE cliente_cubicaje TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE ticket TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE pago TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE extra TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE maquina_cooperativa TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE trabajo_maquinaria TO authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated;

DO $$
DECLARE
  tabla TEXT;
BEGIN
  FOREACH tabla IN ARRAY ARRAY['rol', 'usuario', 'usuario_rol', 'transportista', 'vehiculo', 'lugar', 'cliente', 'material', 'cliente_cubicaje', 'ticket', 'pago', 'extra', 'maquina_cooperativa', 'trabajo_maquinaria']
  LOOP
    EXECUTE format('CREATE POLICY admin_all ON %I FOR ALL TO authenticated USING (public.usuario_tiene_rol(''administrador'')) WITH CHECK (public.usuario_tiene_rol(''administrador''))', tabla);
  END LOOP;
END $$;

DO $$
DECLARE
  tabla TEXT;
BEGIN
  FOREACH tabla IN ARRAY ARRAY['transportista', 'vehiculo', 'lugar', 'cliente', 'material', 'cliente_cubicaje', 'ticket', 'pago', 'extra', 'maquina_cooperativa', 'trabajo_maquinaria']
  LOOP
    EXECUTE format('CREATE POLICY gerencia_all ON %I FOR ALL TO authenticated USING (public.usuario_tiene_rol(''gerencia'')) WITH CHECK (public.usuario_tiene_rol(''gerencia''))', tabla);
  END LOOP;
END $$;

DO $$
DECLARE
  tabla TEXT;
BEGIN
  FOREACH tabla IN ARRAY ARRAY['transportista', 'vehiculo', 'lugar', 'cliente', 'material', 'cliente_cubicaje', 'ticket', 'extra', 'maquina_cooperativa', 'trabajo_maquinaria']
  LOOP
    EXECUTE format('CREATE POLICY despachador_select ON %I FOR SELECT TO authenticated USING (public.usuario_tiene_rol(''despachador''))', tabla);
  END LOOP;
END $$;

CREATE POLICY despachador_insert_ticket ON ticket FOR INSERT TO authenticated WITH CHECK (public.usuario_tiene_rol('despachador'));
CREATE POLICY despachador_update_ticket ON ticket FOR UPDATE TO authenticated USING (public.usuario_tiene_rol('despachador')) WITH CHECK (public.usuario_tiene_rol('despachador'));
CREATE POLICY despachador_insert_extra ON extra FOR INSERT TO authenticated WITH CHECK (public.usuario_tiene_rol('despachador'));
CREATE POLICY despachador_update_extra ON extra FOR UPDATE TO authenticated USING (public.usuario_tiene_rol('despachador')) WITH CHECK (public.usuario_tiene_rol('despachador'));
CREATE POLICY despachador_insert_maquina_cooperativa ON maquina_cooperativa FOR INSERT TO authenticated WITH CHECK (public.usuario_tiene_rol('despachador'));
CREATE POLICY despachador_update_maquina_cooperativa ON maquina_cooperativa FOR UPDATE TO authenticated USING (public.usuario_tiene_rol('despachador')) WITH CHECK (public.usuario_tiene_rol('despachador'));
CREATE POLICY despachador_insert_transportista ON transportista FOR INSERT TO authenticated WITH CHECK (public.usuario_tiene_rol('despachador'));
CREATE POLICY despachador_update_transportista ON transportista FOR UPDATE TO authenticated USING (public.usuario_tiene_rol('despachador')) WITH CHECK (public.usuario_tiene_rol('despachador'));

CREATE POLICY usuario_select_self ON usuario FOR SELECT TO authenticated USING (auth_user_id = auth.uid());

ALTER VIEW vista_ticket_detalle SET (security_invoker = true);
GRANT SELECT ON vista_ticket_detalle TO authenticated;
REVOKE ALL ON vista_ticket_detalle FROM anon;

CREATE TRIGGER trg_pago_updated_at BEFORE UPDATE ON pago FOR EACH ROW EXECUTE FUNCTION actualizar_updated_at();
CREATE TRIGGER trg_extra_updated_at BEFORE UPDATE ON extra FOR EACH ROW EXECUTE FUNCTION actualizar_updated_at();
CREATE TRIGGER trg_maquina_cooperativa_updated_at BEFORE UPDATE ON maquina_cooperativa FOR EACH ROW EXECUTE FUNCTION actualizar_updated_at();
CREATE TRIGGER trg_trabajo_maquinaria_updated_at BEFORE UPDATE ON trabajo_maquinaria FOR EACH ROW EXECUTE FUNCTION actualizar_updated_at();
CREATE TRIGGER trg_rol_updated_at BEFORE UPDATE ON rol FOR EACH ROW EXECUTE FUNCTION actualizar_updated_at();
CREATE TRIGGER trg_usuario_rol_updated_at BEFORE UPDATE ON usuario_rol FOR EACH ROW EXECUTE FUNCTION actualizar_updated_at();
CREATE TRIGGER trg_cliente_cubicaje_updated_at BEFORE UPDATE ON cliente_cubicaje FOR EACH ROW EXECUTE FUNCTION actualizar_updated_at();

-- ============================================================
-- MIGRACIÓN: campos de contacto para notificaciones (CallMeBot + Gmail)
-- Ejecutar solo si la tabla transportista ya existe en producción
-- ============================================================
ALTER TABLE transportista ADD COLUMN IF NOT EXISTS tra_telefono VARCHAR(20);
ALTER TABLE transportista ADD COLUMN IF NOT EXISTS tra_correo VARCHAR(100);

-- ============================================================
-- TABLA: notificacion_alerta
-- Registra cada notificación enviada o programada a 24h
-- ============================================================
CREATE TABLE IF NOT EXISTS notificacion_alerta (
  nal_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tic_id BIGINT NOT NULL REFERENCES ticket(tic_id) ON DELETE CASCADE,
  nal_tipo TEXT NOT NULL,            -- 'despachado_con_alerta' | 'pendiente_expiracion'
  nal_nivel_riesgo TEXT NOT NULL,    -- 'Medio' | 'Alto'
  nal_estado TEXT NOT NULL DEFAULT 'pendiente',  -- 'pendiente' | 'enviada' | 'fallida'
  nal_canal TEXT NOT NULL DEFAULT 'ambos',       -- 'whatsapp' | 'email' | 'ambos'
  nal_destinatario_nombre VARCHAR(200),
  nal_destinatario_telefono VARCHAR(20),
  nal_destinatario_correo VARCHAR(100),
  nal_placa VARCHAR(20),
  nal_mensaje TEXT,
  nal_programada_para TIMESTAMPTZ,   -- para el timer de 24h (NULL = inmediata)
  nal_enviada_en TIMESTAMPTZ,
  nal_error TEXT,                    -- mensaje de error si nal_estado = 'fallida'
  usr_creado_por BIGINT REFERENCES usuario(usr_id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT chk_nal_tipo CHECK (nal_tipo IN ('despachado_con_alerta', 'pendiente_expiracion')),
  CONSTRAINT chk_nal_estado CHECK (nal_estado IN ('pendiente', 'enviada', 'fallida')),
  CONSTRAINT chk_nal_canal CHECK (nal_canal IN ('whatsapp', 'email', 'ambos'))
);

CREATE INDEX IF NOT EXISTS idx_nal_tic_id ON notificacion_alerta(tic_id);
CREATE INDEX IF NOT EXISTS idx_nal_estado ON notificacion_alerta(nal_estado);
CREATE INDEX IF NOT EXISTS idx_nal_programada ON notificacion_alerta(nal_programada_para) WHERE nal_estado = 'pendiente';

CREATE TRIGGER trg_notificacion_alerta_updated_at
  BEFORE UPDATE ON notificacion_alerta
  FOR EACH ROW EXECUTE FUNCTION actualizar_updated_at();

-- Permisos RLS para notificacion_alerta
REVOKE ALL ON TABLE notificacion_alerta FROM anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE notificacion_alerta TO authenticated;

CREATE POLICY admin_all ON notificacion_alerta FOR ALL TO authenticated
  USING (public.usuario_tiene_rol('administrador'))
  WITH CHECK (public.usuario_tiene_rol('administrador'));

CREATE POLICY gerencia_all ON notificacion_alerta FOR ALL TO authenticated
  USING (public.usuario_tiene_rol('gerencia'))
  WITH CHECK (public.usuario_tiene_rol('gerencia'));

CREATE POLICY despachador_select ON notificacion_alerta FOR SELECT TO authenticated
  USING (public.usuario_tiene_rol('despachador'));

CREATE POLICY despachador_insert ON notificacion_alerta FOR INSERT TO authenticated
  WITH CHECK (public.usuario_tiene_rol('despachador'));

